export const LOADING_PAGE: string = 'LoadingPage'
export const LOGIN: string = 'Login'
export const HOME: string = 'Home'
export const RESULTS: string = 'Results'
export const PROFILE: string = 'Profile'
